/-
  DREAMED, UNREVIEWED. See `docs/dreamed/README.md`. Not owner-authored, not part of the
  `verify` lake target, not wired into `physics/*.toml` or `tests/test_verify.sh`.

  Lean attestation for the dreamed essay `docs/dreamed/logic-bloch-phase.md`.

  Source of the seed (owner-authored, this session, verbatim):

      "\phi cannot be a truth-value, that makes sense. but is there another logical
       quantity it _can_ represent? e.g. provability in general, or something entirely
       different?"

  and, earlier (owner-authored, chat export "Falsifiability and Logical Boundaries",
  2025-08-16, verbatim):

      "What about encoding true/false in the phase of provable as unprovable's
       antipode?"

  The predecessor essay `logic-bloch-gates.md` established the NEGATIVE result
  (`LogicGates.lean`, `no_torsion_of_invariant`): the equatorial angle cannot be a
  Kleene/Priest third truth value, because a circle admits no rotation-covariant linear
  order. This file supports the CONSTRUCTIVE follow-up: it formalises three of the four
  filters that any candidate reading of the phase must pass, and then discharges the
  filter-3 failure of the two candidates the owner named first.

  Reading the Lean symbols back into the essay's language:

    `P`                 the set of PROPOSITIONS (or of formalisations, derivations,
                        theories -- the file is deliberately agnostic; the essay names
                        the reading per candidate).
    `G`                 the group in which the phase lives. `U(1)` is the intended
                        instance. Nothing below needs it to be `U(1)` specifically, and
                        that generality is the point: the obstructions are group facts,
                        so they bind every candidate that claims a composable,
                        invertible phase.
    `f : P → G`         an ABSOLUTE phase assignment: one group element per proposition.
                        Filter 1 says this object is not observable.
    `rel f p q`         the RELATIVE phase `(f p)⁻¹ * f q`. Filter 1 says this is the
                        observable content, and `rel_gauge` says exactly how much of
                        `f` it forgets: a global left translation, i.e. the global
                        phase.
    `d : P → P → G` with the chain rule
                        relative-phase data given directly, without an `f`. `rel_of_chain`
                        says every such `d` comes from some `f` once a basepoint is
                        chosen: relative data and "absolute data modulo a constant" are
                        the same thing. This is the gauge-freedom reading (essay
                        candidate 4) stated as a theorem rather than as an analogy.
    `act : G → S → S`, `t : S → Bool`
                        filter 2. `act` is the phase group acting on states; `t` is a
                        truth measurement. If `t` is invariant under `act` and `act` is
                        transitive, `t` cannot separate any two states at all.
    `op : P → P → P` idempotent, `f (op a b) = f a * f b`
                        filter 3, and the file's main negative result. `op` is the
                        combining operation of the candidate logic: conjunction, join,
                        "and here is a second proof of the same thing", Artemov's `+`
                        on proof terms. Every one of those is IDEMPOTENT, and an
                        idempotent element of a group is the identity, so the phase
                        collapses to a constant.
    `f : A →+ ℤ`        candidate 2 (proof-relevance). The identity type of the circle
                        has `π₁ = ℤ` (Licata-Shulman 2013), and `ℤ` is torsion-free,
                        while `U(1)` is generated by its torsion (the roots of unity).
                        `torsion_killed_by_int_hom` is the resulting mismatch: no
                        ℤ-valued invariant sees a torsion element at all.

  EXPLICITLY OUT OF SCOPE (do not read this file as more than it is):
    - There is NO `U(1)` here, no circle group, no Bloch sphere, no Hilbert space and no
      quantum mechanics of any kind. Everything is stated for an abstract group `G`, and
      the step "`U(1)` is a group, so this applies" is taken in the ESSAY, in prose.
    - There is NO provability logic here. `□`, Loeb's axiom `□(□A → A) → □A`, GL's
      Kripke frames and Solovay's arithmetical completeness theorems are DISCUSSED in
      the essay and proved nowhere in this repo. `box_phase_trivial` below models `□`
      only by the single property it needs (that its algebra's meet is idempotent), and
      that modelling step is an essay-level claim, not a Lean-level one.
    - There is NO homotopy type theory here. `π₁(S¹) ≅ ℤ` is CITED in the essay, not
      formalised; this file uses only the downstream algebraic fact that `ℤ` is
      torsion-free. The `A` in `torsion_killed_by_int_hom` is a bare additive group and
      reading it as a fundamental group is the essay's speculation.
    - `no_torsion_of_invariant` (the predecessor's central negative result) is NOT
      restated or reproved here. This file assumes it and builds forward.
    - Nothing here says which candidate is RIGHT. The theorems are eliminative: they say
      what a phase reading cannot be. The ranking in the essay is a recommendation
      awaiting the owner's ruling and is not a theorem.
-/
import Mathlib.Algebra.Group.Basic
import Mathlib.Algebra.Group.Hom.Defs
import Mathlib.Order.Lattice
import Mathlib.Data.Int.Basic
import Mathlib.Algebra.Order.Ring.Int

namespace Toesnail.LogicPhase

universe u v w

/-! ## Filter 1: only relative phase is observable

A global phase is unphysical. The logical content of that sentence is that the object
carrying meaning is not `f : P → G` but the two-place difference `rel f`, and that `rel`
forgets exactly a global left translation and nothing else. -/

section Relative

variable {P : Type u} {G : Type v} [Group G]

/-- The relative phase between two propositions. Two-place BY CONSTRUCTION: this is the
    arity move the essay's filter 1 is about. -/
def rel (f : P → G) (p q : P) : G := (f p)⁻¹ * f q

/-- **Global phase is invisible.** Left-translating every proposition's phase by a fixed
    `c` changes no relative phase. -/
theorem rel_gauge (f : P → G) (c : G) (p q : P) :
    rel (fun x => c * f x) p q = rel f p q := by
  simp [rel, mul_assoc]

/-- A proposition has no phase relative to itself: the diagonal is trivial. Logically,
    "how does this proposition stand to itself" is not a question. -/
theorem rel_self (f : P → G) (p : P) : rel f p p = 1 := by
  simp [rel]

/-- Relative phases compose along a chain of references. This is filter 3's positive
    half: the quantity IS composable. -/
theorem rel_chain (f : P → G) (p q r : P) : rel f p q * rel f q r = rel f p r := by
  simp [rel, mul_assoc]

/-- ...and invertible: reversing the reference inverts the phase. -/
theorem rel_inv (f : P → G) (p q : P) : (rel f p q)⁻¹ = rel f q p := by
  simp [rel]

/-- **Converse: relative data determines absolute data up to one global constant.**
    Any two-place `d` obeying the chain rule is `rel f` for the `f` obtained by measuring
    everything against an arbitrary basepoint `p₀`.

    So "the phase is only ever relative" and "the phase is an absolute assignment modulo
    a global constant" are the SAME statement. That is precisely the structure of a gauge
    freedom, and it is the essay's candidate 4 stated as a theorem. -/
theorem rel_of_chain (d : P → P → G) (hchain : ∀ p q r, d p q * d q r = d p r)
    (p₀ : P) (p q : P) : d p q = rel (fun x => d p₀ x) p q := by
  have h := hchain p₀ p q
  simp only [rel]
  rw [← h, inv_mul_cancel_left]

/-- **Gauge rigidity.** If two absolute assignments have identical relative data, they
    differ by exactly one global constant. Nothing more, nothing less: the gauge group of
    a phase assignment is `G` acting by global translation, and it acts freely on the
    quotient's fibres. -/
theorem gauge_rigidity (f g : P → G) (p₀ : P) (h : ∀ p q, rel f p q = rel g p q) (p : P) :
    g p = (g p₀ * (f p₀)⁻¹) * f p := by
  have hp := h p₀ p
  simp only [rel] at hp
  rw [mul_assoc]
  rw [hp]
  simp [← mul_assoc]

end Relative

/-! ## Filter 2: a phase-invariant truth measurement is blind to the phase

Phase gates leave every computational-basis statistic fixed (`logic-bloch-gates.md` §2.1a)
and act transitively on the equator (§2.1b). Those two facts together are not "the phase
is hard to measure"; they are "the truth question cannot distinguish ANY two phases". -/

section Blind

variable {S : Type u} {G : Type v}

/-- **Invariance plus transitivity is total blindness.** If a two-outcome measurement `t`
    is invariant under the phase action, and the phase action is transitive on the state
    set, then `t` takes the same value at every state whatsoever.

    Stated with `Bool` because a truth measurement has two outcomes; nothing in the proof
    uses that, and the same argument runs for any codomain. -/
theorem truth_blind_of_transitive (act : G → S → S) (t : S → Bool)
    (hinv : ∀ g s, t (act g s) = t s) (htrans : ∀ s s' : S, ∃ g, act g s = s')
    (s s' : S) : t s = t s' := by
  obtain ⟨g, hg⟩ := htrans s s'
  rw [← hg, hinv]

/-- The same statement in its contrapositive form, which is how the essay uses it: if a
    truth measurement separates two states, then the phase action is NOT transitive on
    them, so an invariant reading of the phase owes an account of what breaks
    transitivity. -/
theorem not_transitive_of_separating (act : G → S → S) (t : S → Bool)
    (hinv : ∀ g s, t (act g s) = t s) {s s' : S} (hsep : t s ≠ t s') :
    ¬ (∀ s s' : S, ∃ g, act g s = s') := fun htrans =>
  hsep (truth_blind_of_transitive act t hinv htrans s s')

end Blind

/-! ## Filter 3: idempotence and group structure are incompatible

This is the file's main negative result and the essay's sharpest filter. Every candidate
that combines two pieces of logical support by a JOIN -- conjunction, disjunction, "and
here is a second, independent proof", Artemov's `+` on proof polynomials, the modal `□`
of a normal modal logic through `□(A ∧ B) = □A ∧ □B` -- combines them IDEMPOTENTLY. A
group has no nontrivial idempotents. So no such candidate can carry a nonconstant
group-valued phase. -/

section Idempotent

variable {G : Type v} [Group G]

/-- In a group, the only idempotent is the identity. One line, and it is the whole
    obstruction. -/
theorem idem_eq_one {g : G} (h : g * g = g) : g = 1 := by
  have h' : g⁻¹ * (g * g) = g⁻¹ * g := by rw [h]
  simpa using h'

variable {L : Type u}

/-- **The filter, in general form.** If `f` turns a combining operation `op` into the
    group multiplication, and `op` is idempotent, then `f` is constantly the identity.

    No commutativity, no associativity, no order, no finiteness: idempotence of `op` at
    each point alone kills it. That generality is what makes this a usable filter rather
    than a remark about one logic. -/
theorem phase_trivial_of_idempotent (op : L → L → L) (f : L → G)
    (hom : ∀ a b, f (op a b) = f a * f b) (idem : ∀ a, op a a = a) (a : L) :
    f a = 1 := by
  have : f a * f a = f a := by rw [← hom a a, idem a]
  exact idem_eq_one this

/-- Lattice form: a group-valued homomorphism out of a join-semilattice is trivial.
    Read `⊔` as "combine the support for these two claims". -/
theorem phase_trivial_of_sup [SemilatticeSup L] (f : L → G)
    (hom : ∀ a b, f (a ⊔ b) = f a * f b) (a : L) : f a = 1 :=
  phase_trivial_of_idempotent (· ⊔ ·) f hom (fun a => sup_idem a) a

/-- Meet form, which is the one the modal candidate needs: in any normal modal logic the
    box distributes over conjunction, and conjunction is idempotent. -/
theorem phase_trivial_of_inf [SemilatticeInf L] (f : L → G)
    (hom : ∀ a b, f (a ⊓ b) = f a * f b) (a : L) : f a = 1 :=
  phase_trivial_of_idempotent (· ⊓ ·) f hom (fun a => inf_idem a) a

/-- **The modal candidate fails filter 3.** Model `□` as an operator on a meet-semilattice
    of propositions that distributes over conjunction -- the K axiom's algebraic content,
    shared by every normal modal logic including GL. Then any phase `f` defined on
    provability-facts and multiplicative over conjunction is constant.

    The essay states plainly what this does and does not show: it does not touch Loeb's
    axiom, GL's frames, or Solovay's completeness theorems. It shows that the ONE
    structural property `□` inherits from `∧` is already enough to forbid a `U(1)`
    grading, so no refinement of the modality rescues the reading.

    NOTE, and it strengthens the finding rather than weakening it: the hypothesis `_hbox`
    (the K axiom's algebraic content) is DELIBERATELY UNUSED. It is stated because it is
    the property one reaches for, and then the proof does not need it: the conclusion
    already follows from `f`'s own multiplicativity over `⊓`. So the obstruction is not
    special to `□` at all -- it lands on any operator whatsoever whose values are graded
    by a group-valued phase over conjunction. Nothing about GL, Loeb or provability can
    be blamed for the failure, and nothing about them can repair it. -/
theorem box_phase_trivial [SemilatticeInf L] (box : L → L)
    (_hbox : ∀ a b, box (a ⊓ b) = box a ⊓ box b) (f : L → G)
    (hom : ∀ a b, f (a ⊓ b) = f a * f b) (a : L) : f (box a) = 1 :=
  phase_trivial_of_inf f hom (box a)

/-- The Artemov-flavoured corollary, kept abstract. In the Logic of Proofs the sum `s + t`
    of two proof terms proves everything either proves, and `t + t` proves exactly what
    `t` does. That idempotence is all the theorem needs, so any `U(1)`-valued reading of
    "which proof" that is additive over proof-sum is constant. The identification of `+`
    with an idempotent `op` is the ESSAY's modelling claim, not Lean's. -/
theorem proof_sum_phase_trivial (sum : L → L → L) (hidem : ∀ t, sum t t = t)
    (f : L → G) (hom : ∀ s t, f (sum s t) = f s * f t) (t : L) : f t = 1 :=
  phase_trivial_of_idempotent sum f hom hidem t

end Idempotent

/-! ## Candidate 2: proof-relevance gives ℤ, and ℤ is not the circle

Homotopy type theory makes a proposition a TYPE, so it can have many distinct proofs, and
the identity type of the circle has fundamental group `ℤ` (Licata-Shulman 2013). That is a
genuine winding number, which is why the candidate passes filter 3 where the others fail.
But `ℤ` and `U(1)` are different groups in exactly the way that matters here: `U(1)` is
generated by its torsion elements (the roots of unity), and `ℤ` has none. -/

section TorsionFree

/-- **A ℤ-valued invariant cannot see a torsion element.** If `n • a = 0` for some `n ≠ 0`
    then every additive homomorphism to `ℤ` sends `a` to `0`.

    Read logically: a winding number counts loops, and an element of finite order has no
    net winding. Any candidate whose invariant is a winding number is therefore blind to
    precisely the part of `U(1)` -- the roots of unity -- that `logic-bloch-gates.md` §4.4
    identified as the phase the real gates actually write (`CCZ` writes `±1`). -/
theorem torsion_killed_by_int_hom {A : Type u} [AddCommGroup A] (f : A →+ ℤ)
    {a : A} {n : ℕ} (hn : n ≠ 0) (ha : n • a = 0) : f a = 0 := by
  have h : (n : ℤ) * f a = 0 := by
    have hfa : f (n • a) = n • f a := map_nsmul f n a
    rw [ha] at hfa
    simpa [nsmul_eq_mul] using hfa.symm
  rcases mul_eq_zero.mp h with h1 | h2
  · exact absurd (Nat.cast_eq_zero.mp h1) hn
  · exact h2

/-- Consequence: a nontrivial torsion element is never separated from `0` by a ℤ-valued
    invariant, so no such invariant is injective on a group with torsion.

    This is the honest limit on candidate 2. Proof-relevance supplies a group and a
    winding number, which is what filter 3 asked for; it does not supply `U(1)`, and
    identifying the two would be a choice, not a derivation. -/
theorem no_injective_int_hom_of_torsion {A : Type u} [AddCommGroup A] (f : A →+ ℤ)
    {a : A} {n : ℕ} (hn : n ≠ 0) (ha : n • a = 0) (ha0 : a ≠ 0) :
    ¬ Function.Injective f := by
  intro hinj
  exact ha0 (hinj (by rw [torsion_killed_by_int_hom f hn ha, map_zero]))

end TorsionFree

/-! ## What survives all three filters

Collecting the positive content: the relative-phase construction of the first section
passes every filter simultaneously. It is two-place (filter 1), it is invisible to any
invariant one-place measurement (filter 2), and it composes and inverts (filter 3)
WITHOUT being idempotent -- because `rel f p q * rel f p q ≠ rel f p q` in general, the
combining operation is chaining along a path, not joining two pieces of support.

That difference is the essay's conclusion in one line: a phase can encode how two
formalisations are related along a path between them, and cannot encode how much support
a single proposition has. -/

section Survivor

variable {P : Type u} {G : Type v} [Group G]

/-- Chaining is NOT idempotent, which is exactly why it escapes `phase_trivial_of_idempotent`.
    Witness: any `f`, `p`, `q` whose relative phase is not `1`. -/
theorem rel_not_idempotent (f : P → G) (p q : P) (h : rel f p q ≠ 1) :
    rel f p q * rel f p q ≠ rel f p q := fun hidem => h (idem_eq_one hidem)

/-- And relative phase is genuinely nonconstant whenever the absolute assignment is,
    so the survivor is not trivial for the boring reason. -/
theorem rel_nontrivial (f : P → G) {p q : P} (h : f p ≠ f q) : rel f p q ≠ 1 := by
  intro hc
  apply h
  have : f p * rel f p q = f p := by rw [hc, mul_one]
  rw [rel, ← mul_assoc, mul_inv_cancel, one_mul] at this
  exact this.symm

end Survivor

end Toesnail.LogicPhase
