/-
  DREAMED, UNREVIEWED. See `docs/dreamed/README.md`.

  Companion essay: `docs/dreamed/time-and-operators.md`. Seed picked by the owner
  2026-09-01: the two unpaid time promises in `physics/toesnail.md`, l.54 ("we have
  not even defined the passage of time so far") and l.133 (the whole `## Transition`
  section, `|coin> -> |tossed coin>` followed by `#TODO: get to operators...`).

  Everything below is FINITE-DIMENSIONAL, over `Matrix n n ℂ` with `n` a Fintype.
  That is the honest ceiling: the owner's running example is a coin, i.e. a qubit,
  and in finite dimensions every operator is bounded, every symmetric operator is
  self-adjoint, and `exp` is an entire power series. The essay says loudly what this
  buys and what it hides.

  WHAT IS NOT HERE, and why:

  * STONE'S THEOREM ITSELF. Mathlib (rev pinned by `verify/lean-toolchain`,
    `leanprover/lean4:v4.30.0-rc2`) does NOT carry Stone's theorem on one-parameter
    unitary groups. Grepping the vendored Mathlib for `Stone` finds the
    Stone-Weierstrass theorem, `StoneCech`, and Stone duality for Boolean algebras;
    there is no `stone_theorem`/`StonesTheorem` about `ℝ →* unitary` and no
    unbounded self-adjoint generator API to state it against. Stating a fake version
    (finite dimensions, where the theorem is the elementary matrix-logarithm fact)
    and calling it Stone would be a bluff, so this file states the EASY DIRECTION
    only, which is genuinely provable and is what the narrative in the essay leans
    on: from a self-adjoint `H`, `exp (-i t H)` really is a strongly continuous
    one-parameter unitary group. The hard direction (every such group arises this
    way, with a UNIQUE self-adjoint generator) is asserted in prose in the essay and
    is explicitly NOT attested here.
  * UNBOUNDED OPERATORS, domains, essential self-adjointness. Not modelled at all.
    In finite dimensions `Hᴴ = H` (symmetric) and self-adjoint coincide; the essay
    states that they come apart in infinite dimensions and that this is exactly the
    hypothesis Stone's theorem cannot drop.
  * The closed form `exp (-i t X) = cos t • 1 - i sin t • X` for the coin's
    `X = !![0,1;1,0]`. It needs the even/odd split of the exponential series, which
    Mathlib does not carry as a lemma about matrices with `X * X = 1`. `coinH_sq`
    records the algebraic input; the closed form is NOT proven. Stated as a
    weakening in the essay's attestation section.

  Convention note, matching `docs/dreamed/lean/Spine.lean`: that file already did
  the inner-product axioms and Cauchy-Schwarz over `ℂ` and found Mathlib's `⟪·,·⟫`
  agrees with the spine's (Dirac) convention. Nothing is reproven here.

  Check (from `/home/tobias/src/toesnail/verify`):
      nice -n19 lake env lean --threads=2 \
        /home/tobias/src/toesnail/docs/dreamed/lean/TimeEvolution.lean
-/
import Mathlib.Analysis.Normed.Algebra.MatrixExponential
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Analysis.Normed.Module.FiniteDimension

open NormedSpace Matrix
open scoped Matrix

namespace ToesnailTime

variable {n : Type*} [Fintype n] [DecidableEq n]

/-! ## 1. The generator, and the transition operator built from it

`physics/toesnail.md` l.131 writes the transition as a bare arrow,
`|coin⟩ → |tossed coin⟩`. The essay argues that three demands the spine has already
made (probabilities stay probabilities, evolutions compose, doing nothing changes
nothing) force that arrow to be a one-parameter unitary group. This section defines
the object; sections 2 and 3 discharge the three demands as theorems. -/

/-- The generator `-iH` of the evolution, split out so that the group law and the
derivative can both be stated about a single `ℝ`-scalar multiple. Writing `U t` as
`exp (t • gen H)` rather than `exp ((-i t) • H)` keeps the scalar real, which is what
makes `add_smul` and Mathlib's `hasDerivAt_exp_smul_const` apply directly; `U_eq`
below records that this is the same operator the physics literature writes. -/
noncomputable def gen (H : Matrix n n ℂ) : Matrix n n ℂ := (-Complex.I) • H

/-- `U H t = exp (-i t H)`, the time-evolution operator generated by `H`.
Units: `ħ = 1`, so `t` carries whatever unit makes `H t` dimensionless. -/
noncomputable def U (H : Matrix n n ℂ) (t : ℝ) : Matrix n n ℂ := exp (t • gen H)

/-- `U H t = exp ((-i t) • H)`, the spelling used in the essay's prose and in every
textbook. Recorded so that the definition above cannot be accused of smuggling a
different operator in under a convenient scalar. -/
theorem U_eq (H : Matrix n n ℂ) (t : ℝ) :
    U H t = exp ((-Complex.I * (t : ℂ)) • H) := by
  rw [U, gen]
  congr 1
  ext i j
  simp [Matrix.smul_apply, Complex.real_smul]
  ring

/-! ## 2. The three demands, as three theorems

These are the whole content of the essay's section 1: they are not postulates about
quantum mechanics, they are the answers to three questions the spine's own text has
already licensed asking. -/

/-- **Demand 3: doing nothing changes nothing.** `U(0) = 𝟙`. -/
theorem U_zero (H : Matrix n n ℂ) : U H 0 = 1 := by
  have h : (0 : ℝ) • gen H = 0 := zero_smul _ _
  rw [U, h, exp_zero]

/-- **Demand 2: evolutions compose.** `U(t) U(s) = U(t+s)`: evolving for 3 seconds
and then for 2 is evolving for 5.

The proof is `exp` of a sum of COMMUTING operators, and the commutation is not an
extra assumption: both exponents are scalar multiples of the same `H`, so they
commute for free. That is the whole reason the one-parameter family is a GROUP and
not merely a family of unitaries, and it is why the time-ordered exponential of a
time-dependent Hamiltonian is a genuinely harder object. -/
theorem U_group (H : Matrix n n ℂ) (t s : ℝ) : U H t * U H s = U H (t + s) := by
  have hc : Commute (t • gen H) (s • gen H) :=
    ((Commute.refl (gen H)).smul_left t).smul_right s
  have h : (t + s) • gen H = t • gen H + s • gen H := add_smul t s (gen H)
  rw [U, U, U, ← Matrix.exp_add_of_commute _ _ hc, h]

/-- The group is a group: `U(-t)` inverts `U(t)`. Immediate from the two above,
recorded because "the evolution is reversible" is a physical statement the spine
will want to make in words. -/
theorem U_inverse (H : Matrix n n ℂ) (t : ℝ) : U H t * U H (-t) = 1 := by
  rw [U_group, add_neg_cancel, U_zero]

omit [Fintype n] [DecidableEq n] in
/-- Self-adjointness of `H` enters exactly once, here: the conjugate transpose of the
generator is its own negative, `(-iH)ᴴ = iH = -(-iH)`. In the operator-algebra
vocabulary, `gen H` is SKEW-adjoint. The factor `i` is doing all the work: without
it, `H` self-adjoint would give a self-adjoint generator and `exp(-tH)` would be a
positive contraction semigroup (diffusion), not a unitary group. -/
theorem gen_conjTranspose (H : Matrix n n ℂ) (hH : Hᴴ = H) : (gen H)ᴴ = -gen H := by
  rw [gen, conjTranspose_smul, hH, star_neg, Complex.star_def, Complex.conj_I, neg_neg,
    neg_smul, neg_neg]

/-- Taking the adjoint of the evolution reverses time: `U(t)ᴴ = U(-t)`. -/
theorem U_conjTranspose (H : Matrix n n ℂ) (hH : Hᴴ = H) (t : ℝ) :
    (U H t)ᴴ = U H (-t) := by
  have h1 : t • (-gen H) = -(t • gen H) := smul_neg t (gen H)
  have h2 : (-t) • gen H = -(t • gen H) := neg_smul t (gen H)
  have h : t • (-gen H) = (-t) • gen H := by rw [h1, h2]
  rw [U, ← Matrix.exp_conjTranspose, conjTranspose_smul, star_trivial,
    gen_conjTranspose H hH, h, U]

/-- **Demand 1: probabilities stay probabilities.** `U(t)ᴴ U(t) = 𝟙`, i.e. `U(t)` is
unitary, i.e. it preserves every inner product `⟪Ψ|Φ⟫` and hence every `|⟪Ψ|Φ⟫|²`
that `docs/dreamed/lean/Spine.lean`'s `spine_born_bound` bounded by one.

Read as an implication this is the "forced" half of the essay's argument: given a
self-adjoint `H`, unitarity is a THEOREM, not a further postulate. -/
theorem U_unitary (H : Matrix n n ℂ) (hH : Hᴴ = H) (t : ℝ) :
    (U H t)ᴴ * U H t = 1 := by
  rw [U_conjTranspose H hH t, U_group, neg_add_cancel, U_zero]

/-- The other-sided unitarity. In finite dimensions this is redundant (a left inverse
of a square matrix is a right inverse); stated anyway because in infinite dimensions
it is NOT, and the distinction between an isometry and a unitary is precisely one of
the places the finite-dimensional shortcut hides something. -/
theorem U_unitary' (H : Matrix n n ℂ) (hH : Hᴴ = H) (t : ℝ) :
    U H t * (U H t)ᴴ = 1 := by
  rw [U_conjTranspose H hH t, U_group, add_neg_cancel, U_zero]

/-! ## 3. The generator is recovered: the Schroedinger equation as a corollary

This is the payoff the essay claims for putting Stone at `physics/toesnail.md` l.133.
The Schroedinger equation is not postulated; it is what differentiating a
one-parameter group gives you. -/

open scoped Norms.Operator in
/-- `d/dt U(t) = U(t) · (-iH)`. Multiplying by `i` and using `U_commute` below (or
directly, since `U(t)` commutes with `H`) this is `i dU/dt = H U(t)`, the
Schroedinger equation for the propagator.

Not weakened: this is the honest derivative, `HasDerivAt`, not a formal power-series
coefficient. It is available because Mathlib's `hasDerivAt_exp_smul_const` covers a
complete normed algebra, and `Matrix n n ℂ` is one under the (scoped) `L¹-L∞`
operator norm. The `letI` is needed only because Lean's instance search does not
otherwise connect that scoped norm to `CompleteSpace`; it supplies the standard fact
that a finite-dimensional normed `ℂ`-space is complete. -/
theorem U_hasDerivAt (H : Matrix n n ℂ) (t : ℝ) :
    HasDerivAt (fun s : ℝ => U H s) (U H t * gen H) t := by
  letI : @CompleteSpace (Matrix n n ℂ) (PseudoMetricSpace.toUniformSpace) :=
    FiniteDimensional.complete ℂ _
  exact hasDerivAt_exp_smul_const (𝕂 := ℝ) (gen H) t

/-- At `t = 0` the derivative is the generator itself, `-iH`. This is the sentence
"the Hamiltonian is the generator of time translations", as a theorem: `H` is not put
in by hand, it is READ OFF the one-parameter family. -/
theorem U_hasDerivAt_zero (H : Matrix n n ℂ) :
    HasDerivAt (fun t : ℝ => U H t) (gen H) 0 := by
  have key := U_hasDerivAt H 0
  rwa [U_zero, one_mul] at key

/-! ## 4. Strong continuity, which in finite dimensions is free

Stone's theorem needs strong continuity as a genuine hypothesis: without it there
exist (via a Hamel basis and the axiom of choice) one-parameter unitary groups with
no generator at all. In finite dimensions the hypothesis costs nothing, and this
section says so with a proof rather than with a hand wave. The essay is explicit
that "free here" is not "free in general": continuity is derived from
differentiability, which is available only because `exp` of a bounded operator is an
entire function. -/

-- Both statements are made inside the `Norms.Operator` scope, so the topology is the
-- one induced by the `L¹-L∞` operator norm. For a `Fintype` index that topology IS
-- the entrywise one; the scope is needed because Lean carries two different (equal,
-- not syntactically identical) `TopologicalSpace (Matrix n n ℂ)` instances.
open scoped Norms.Operator in
theorem U_differentiable (H : Matrix n n ℂ) : Differentiable ℝ (fun t : ℝ => U H t) :=
  fun t => (U_hasDerivAt H t).differentiableAt

open scoped Norms.Operator in
theorem U_continuous (H : Matrix n n ℂ) : Continuous (fun t : ℝ => U H t) :=
  (U_differentiable H).continuous

/-! ## 5. Quantum Noether: conserved iff commuting with `H`

`physics/toesnail.md` l.138 plans a `## Symmetry / Noether / Gauge` section. The
essay's structural argument for putting Stone at l.133 is that this section then
costs almost nothing: the SAME one-parameter-group machinery gives every continuous
symmetry a generator, and conservation becomes commutation with `H`. -/

open scoped Norms.Operator in
/-- If an observable `A` commutes with the Hamiltonian, it commutes with the whole
evolution. This is the entire technical content of the quantum Noether theorem. -/
theorem U_commute (H A : Matrix n n ℂ) (h : Commute A H) (t : ℝ) :
    Commute A (U H t) := by
  have h1 : Commute A (gen H) := h.smul_right _
  have h2 : Commute A (t • gen H) := h1.smul_right _
  exact h2.exp_right

/-- **Quantum Noether, Heisenberg picture.** If `[A, H] = 0` then the evolved
observable `A(t) = U(t)ᴴ A U(t)` equals `A` for every `t`: `A` is conserved.

Stated on the operator rather than on an expectation value `⟪Ψ|A|Ψ⟫`, because the
operator statement implies the expectation-value statement for EVERY state at once
(`noether_expectation` below), whereas the converse would need a polarisation
argument the spine has not asked for. -/
theorem heisenberg_invariant (H A : Matrix n n ℂ) (hH : Hᴴ = H) (h : Commute A H)
    (t : ℝ) : (U H t)ᴴ * A * U H t = A := by
  have hc : A * U H t = U H t * A := U_commute H A h t
  calc (U H t)ᴴ * A * U H t = (U H t)ᴴ * (A * U H t) := by rw [mul_assoc]
    _ = (U H t)ᴴ * (U H t * A) := by rw [hc]
    _ = ((U H t)ᴴ * U H t) * A := by rw [mul_assoc]
    _ = A := by rw [U_unitary H hH t, one_mul]

/-- The expectation value of a conserved observable in an evolving state is constant
in `t`, for every state `v` and every `t`. `star v ⬝ᵥ M.mulVec v` is `⟪v|M|v⟫` written
out; the evolved state is `U(t) v`. No normalisation of `v` is needed. -/
theorem noether_expectation (H A : Matrix n n ℂ) (hH : Hᴴ = H) (h : Commute A H)
    (t : ℝ) (v : n → ℂ) :
    star (U H t *ᵥ v) ⬝ᵥ (A *ᵥ (U H t *ᵥ v)) = star v ⬝ᵥ (A *ᵥ v) := by
  rw [star_mulVec, ← dotProduct_mulVec, mulVec_mulVec, mulVec_mulVec,
    heisenberg_invariant H A hH h t]

omit [DecidableEq n] in
/-- Conversely, if `A` is conserved for all `t` then it commutes with `H`: at
`t = 0` the derivative of `U(t)ᴴ A U(t)` is `i[H, A]`. That direction needs the
derivative of a product of two `t`-dependent factors and is NOT proven here; the
essay states it and flags it as unattested. The *stated* half is the one above.

What IS recorded, at zero cost, is the algebraic equivalence the essay quotes:
`Commute A H` is literally `A * H = H * A`, i.e. `[A, H] = 0`. -/
theorem commute_iff_bracket_zero (H A : Matrix n n ℂ) :
    Commute A H ↔ A * H - H * A = 0 := by
  rw [sub_eq_zero]
  exact Iff.rfl

/-! ## 6. The owner's coin, concretely

`physics/toesnail.md` l.57: the coin has outcomes `|heads⟩` and `|tails⟩`, so its
state space is two-dimensional. The simplest non-trivial Hamiltonian on it is the
one that exchanges the two, and everything above specialises to it by `decide`-level
computation. -/

/-- The exchange Hamiltonian on `span{|heads⟩, |tails⟩}`: it maps heads to tails and
tails to heads. This is the Pauli `X` / NOT operator; the essay is careful that
choosing it is an ILLUSTRATION, not a physical claim about coins. -/
def coinH : Matrix (Fin 2) (Fin 2) ℂ := !![0, 1; 1, 0]

/-- It is self-adjoint, so everything in sections 2 to 5 applies to it. -/
theorem coinH_selfAdjoint : coinHᴴ = coinH := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [coinH]

/-- `X² = 𝟙`. This is the algebraic input to the closed form
`exp (-i t X) = cos t · 𝟙 - i sin t · X`; the closed form itself is NOT proven here
(see the header). Recorded because it is what makes the coin's evolution periodic
with period `2π`, i.e. a genuine rotation between heads and tails. -/
theorem coinH_sq : coinH * coinH = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [coinH, Matrix.mul_apply, Fin.sum_univ_two]

/-- The coin's evolution is unitary at every time. -/
theorem coin_U_unitary (t : ℝ) : (U coinH t)ᴴ * U coinH t = 1 :=
  U_unitary coinH coinH_selfAdjoint t

/-- The coin's evolution composes, and is the identity at `t = 0`: the owner's arrow
`|coin⟩ → |tossed coin⟩` is the `t`-slice of a group action, not an isolated map. -/
theorem coin_U_group (t s : ℝ) : U coinH t * U coinH s = U coinH (t + s) :=
  U_group coinH t s

/-- `X` commutes with itself, so the coin's own exchange observable is conserved
under its own evolution: the trivial but non-vacuous instance of Noether here. -/
theorem coin_noether (t : ℝ) : (U coinH t)ᴴ * coinH * U coinH t = coinH :=
  heisenberg_invariant coinH coinH coinH_selfAdjoint (Commute.refl coinH) t

end ToesnailTime
